version: '3.8'

services:
  verifact:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SEARCH_ENGINE=${GOOGLE_SEARCH_ENGINE}
    env_file:
      - .env
